server:
  port: 8888

spring:
  profiles:
    active: production

  application:
    name: cloud-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:'your-github'
          host-key: your-host-key
          host-key-algorithm: your-host-key-algorithm
          private-key: your-private-key
          ignore-local-ssh-settings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
