server:
  port: 0
  http2:
    enabled: true
  compression:
    enabled: true

  ssl:
    key-alias: tomcat
    key-store-type: PKCS12
    key-store: keystore.p12
    key-store-password: 123456

name: yahoo~!

panda:
  age: 55
  name: panda-bear
  weight: 999999