spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: false
    classpath: db/migration

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/spring-anything
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      format_sql: true

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.engine.transaction.internal.TransactionImpl: debug

webclient:
  max-byte-count: 16777216
  read-write-timeout-seconds: 3
  response-timeout-seconds: 15
  connect-timeout-millis: 3000
  max-idle-and-life-time-seconds: 18