spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/spring-anything
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: true

webclient:
  max-byte-count: 16777216
  read-write-timeout-seconds: 3
  response-timeout-seconds: 15
  connect-timeout-millis: 3000
  max-idle-and-life-time-seconds: 18