spring:
  thymeleaf:
    cache: false

  cache:
    type: redis

  threads:
    virtual:
      enabled: true

  session:
    store-type: redis

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

#  flyway:
#    enabled: false
#    baseline-on-migrate: true
#    validate-on-migrate: false
#    classpath: db/migration

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/spring-anything
      driver-class-name: org.h2.Driver
      username: sa
      password:
#      jdbc-url: jdbc:mysql://localhost:3307/batch_test?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
#      driver-class-name: com.mysql.jdbc.Driver
#      username: panda
#      password: bear

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  tomcat:
    keep-alive-timeout: 5000
  port: 8080
  servlet:
    session:
      cookie:
        secure: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    reactor.netty: debug
    com.springanything.config: debug
    com.springanything.aop.LogAspect: debug

webclient:
  max-byte-count: 16777216
  read-write-timeout-seconds: 30
  response-timeout-seconds: 30
  connect-timeout-millis: 3000
  max-idle-and-life-time-seconds: 20

jasypt:
  encryptor:
    password: test
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

app:
  username: ENC(iT5UJ7IhyP9rFLlzbhuUqXKnC2mI20S9)
  password: ENC(T/0aQ/koEXO7eZahX7YcCwhjXHXvKBhR)

springanything:
  conditional: TrUe
