spring:
  retry:
    enabled: true

  thymeleaf:
    cache: false

  cache:
    type: redis

  threads:
    virtual:
      enabled: true

    # mvc:
    #   content-negotiation:
    #     suffix:
    #       enabled: true
    #   pathmatch:
    #     matching-strategy: ant_path_matcher
    #     use-registered-suffix-pattern: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    
    # flyway:
    #   enabled: false
    #   baseline-on-migrate: true
    #   validate-on-migrate: false
    #   classpath: db/migration

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/spring-anything
      driver-class-name: org.h2.Driver
      username: sa
      password:
      # jdbc-url: jdbc:mysql://localhost:3307/batch_test?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      # driver-class-name: com.mysql.jdbc.Driver
      # username: panda
      # password: bear

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        highlight_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  tomcat:
    keep-alive-timeout: 5000
  port: 8080
  servlet:
    session:
      cookie:
        secure: true

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    reactor.netty: debug
    com.springanything.config: debug
    com.springanything.aop.LogAspect: debug

webclient:
  max-byte-count: 16777216
  read-write-timeout-seconds: 30
  response-timeout-seconds: 30
  connect-timeout-millis: 3000
  max-idle-and-life-time-seconds: 20

jasypt:
  encryptor:
    password: test

app:
  username: ENC(n/Wa+KSIgpTEdsQct4bDUHK8utp2+iRiMrCGjMH0LIB+qPM4jjY9oHuDxfnD3O4v)
  password: ENC(iLvJmw702W4E3HGb1Db21zZOdA6OCeOH/tfkuNccf1EcwQgR73rWOFWOQdfavWFq)

springanything:
  conditional: true
