spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  redis:
    host: localhost
    port: 6379

#  flyway:
#    enabled: false
#    baseline-on-migrate: true
#    validate-on-migrate: false
#    classpath: db/migration

  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: panda
#    password: bear
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/spring-anything
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.engine.transaction.internal.TransactionImpl: debug

webclient:
  max-byte-count: 16777216
  read-write-timeout-seconds: 3
  response-timeout-seconds: 15
  connect-timeout-millis: 3000
  max-idle-and-life-time-seconds: 18

jasypt:
  encryptor:
    password: test
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

app:
  username: ENC(iT5UJ7IhyP9rFLlzbhuUqXKnC2mI20S9)
  password: ENC(T/0aQ/koEXO7eZahX7YcCwhjXHXvKBhR)