spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # enable / disable execution by spring batch

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch_test?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: panda
      password: bear

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
