### Success
POST http://localhost:8080/test/nested-validation
Content-Type: application/json

{
  "outerName": "panda",
  "innerNestedRequests": [
    {
      "innerName": "bear"
    },
    {
      "innerName": "panda"
    }
  ]
}

### Fail
POST http://localhost:8080/test/nested-validation
Content-Type: application/json

{
  "outerName": "panda",
  "innerNestedRequests": [
    {
      "innerName": "bear"
    },
    {
      "innerName": "123123"
    }
  ]
}

### Fail By outerName length
POST http://localhost:8080/test/nested-validation
Content-Type: application/json

{
  "outerName": "panda",
  "outerBoolean": 0,
  "innerNestedRequests": [
    {
      "innerName": "bear"
    },
    {
      "innerName": "grizzly"
    }
  ]
}

### Success
POST http://localhost:8080/test/nested-validation/v2
Content-Type: application/json

{
  "outerName": "",
  "outerBoolean": true,
  "innerNestedRequests": [
    {
      "innerName": "a"
    },
    {
      "innerName": "b"
    }
  ]
}
