### Success
POST http://localhost:8080/test/nested-validation
Content-Type: application/json

{
  "outerName": "panda",
  "innerNestedRequests": [
    {
      "innerName": "bear"
    },
    {
      "innerName": "panda"
    }
  ]
}

### Fail
POST http://localhost:8080/test/nested-validation
Content-Type: application/json

{
  "outerName": "panda",
  "innerNestedRequests": [
    {
      "innerName": "bear"
    },
    {
      "innerName": "123123"
    }
  ]
}
