server:
  port: 8080

spring:
  application:
    name: cloud-config
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: cloud-config
      profile: local

management:
  endpoints:
    web:
      exposure:
        include: refresh
